[package]
name = "letterbox"
version = "0.1.0"
edition = "2024"

[features]
default = ["corridor"]
corridor = []
delta = []

[dependencies]
controller = { path = "../controller" }

[build-dependencies]
cbindgen = "0.28.0"
