[package]
name = "mtdynamic"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "busywork"
path = "src/busywork.rs"

[build-dependencies]
cbindgen = "0.26.0"
