[package]
name = "mtdynamic"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[[bin]]
name = "energy_controller"
path = "src/bin/energy_controller.rs"

[build-dependencies]
cbindgen = "0.27.0"

[dependencies]
ctrlc = "3.4.5"
libc = "0.2.166"
rapl-energy = "0.1.19"
