language = "C"
#cpp_compat = true
include_guard = "MTD_MTDYNAMIC"
usize_is_size_t = true
tab_width = 4

[defines]
"feature = delta-based" = "DELTA_BASED"
"feature = corridor-based" = "CORRIDOR_BASED"
