[package]
name = "server"
version = "0.1.0"
edition = "2024"

[lib]
name = "mtd_server"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
controller = { path = "../controller" }
static_init = "1.0.3"
