[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
controller = { path = "../controller" }
ctrlc = "3.4.7"
rapl-energy = { git = "https://github.com/JordyAaldering/rapl-energy.git" }

[dev-dependencies]
rayon = "1.10.0"
