[package]
name = "server"
version = "0.1.0"
edition = "2024"

[lib]
name = "letterbox"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/main.rs"

[features]
default = ["corridor"]
corridor = []
delta = []
genetic = []

[dependencies]
controller = { path = "../controller" }
