[package]
name = "server"
version = "0.1.0"
edition = "2024"

[features]
default = ["corridor"]
corridor = []
delta = []

[dependencies]
controller = { path = "../controller" }
letterbox = { path = "../letterbox" }
