[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
controller = { path = "../controller" }
ctrlc = "3.5.0"
rapl-energy = "0.1.24"
