use std::debug_assert;

use clap::Parser;

use crate::*;

pub struct GeneticController {
    samples: Vec<Sample>,
    population: Vec<Chromosome>,
    immigration_cooldown: usize,
    sort_descending: bool,
    max_threads: u16,
    effective_survival_rate: f32,
    effective_mutation_rate: f32,
    config: GeneticConfig,
    // Debugging metadata
    generation: usize,
    immigration_was_triggered: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Chromosome {
    num_threads: u16,
    power_pct: f32,
    /// The score of this chromosome in the previous generation.
    /// This occurs when the chromosome survived, and mutation did not modify it a lot.
    /// Or when the chromosome was generated by crossover of two similar parents, in which case the score is averaged.
    prev_score: Option<f32>,
    /// The global thread count at the time this chromosome was sampled.
    /// This excludes the threads used by this chromosome itself ([Chromosome::num_threads]).
    /// Note that this can never be exact, as the thread count may change during a sample's execution time.
    /// To somewhat account for this we read the thread count before and after the sample, and take the average.
    global_thread_count: Option<u16>,
}

#[derive(Clone, Debug, Parser)]
pub struct GeneticConfig {
    #[arg(short('s'), long, default_value_t = 20)]
    pub population_size: usize,

    /// Describes the importance of optimising for energy efficiency over runtime performance.
    /// A value of 1 means that only energy efficiency is optimised for, while a value of 0 means that only runtime performance is optimised for.
    ///
    /// Range: [0,1]
    #[arg(long, default_value_t = 0.9)]
    pub energy_preference: f32,

    /// Enable thread control.
    #[arg(long("thread-control"))]
    pub do_thread_control: bool,

    /// Enable power limit control.
    ///
    /// Requires RAPL to be available and the server to be run with root privileges.
    #[arg(long("power-control"))]
    pub do_power_control: bool,
    /// Minimum allowed percentage of the powercap.
    ///
    /// Range: (0,1]
    #[arg(long, default_value_t = 0.1)]
    pub power_min: f32,
    /// Maximum allowed percentage of the powercap.
    ///
    /// Range: (0,1]
    #[arg(long, default_value_t = 1.0)]
    pub power_max: f32,

    /// Enable nudging of chromosomes towards secondary preferences, such as core sharing and power limit proportional to energy preference.
    #[arg(long("nudge"))]
    pub do_nudging: bool,
    /// Upper bound on the influence secondary preferences ("nudges") may have
    /// on a chromosome's score, expressed as a fraction of that score.
    ///
    /// Nudges are applied multiplicatively rather than as a fixed offset, so they can only ever
    /// re-order chromosomes whose raw scores already fall within this fraction of one another;
    /// they can never override a clearly better scoring chromosome.
    /// The effective nudge is additionally capped by [GeneticConfig::nudge_relative_cap] so a fixed
    /// percentage doesn't dominate on flat score landscapes or become irrelevant on steep ones.
    ///
    /// Range: [0,1]
    #[arg(long, default_value_t = 0.05)]
    pub nudge_strength: f32,
    /// Caps the effective nudge strength to this fraction of the current generation's own
    /// relative score spread. This keeps nudges proportional to how much the scores actually
    /// vary this generation, rather than always applying the full [GeneticConfig::nudge_strength].
    ///
    /// Range: [0,1]
    #[arg(long, default_value_t = 0.5)]
    pub nudge_relative_cap: f32,

    /// By default, the first chromosomes will have low thread counts and power limits,
    /// and the last chromosomes will have high thread counts and power limits.
    /// Setting this value to true reverses this order.
    #[arg(long)]
    pub initial_population_descending: bool,

    /// Genetic algorithm survival rate. Controls the fraction of the population that
    /// survives into the next generation as elite individuals.
    ///
    /// Range: (0,1]
    #[arg(long, default_value_t = 0.15)]
    pub survival_rate: f32,
    /// Survival rate decay factor. After each generation, the effective survival rate
    /// is multiplied by this factor. A decay of 0 means that no decay occurs. A decay
    /// of 0.5 means that after every generation, the effective survival rate is halved.
    /// This allows faster convergence when there is a wide range of good configurations,
    /// which would otherwise cause high variability in the selected chromosomes.
    ///
    /// No survival rate decay happens by default.
    ///
    /// Range: [0,1]
    #[arg(long, default_value_t = 0.0)]
    pub survival_rate_decay: f32,

    /// Mutation strength: maximum magnitude of a random perturbation applied to each gene.
    ///
    /// Range: (0,1]
    #[arg(long, default_value_t = 0.01)]
    pub mutation_strength: f32,
    /// Mutation rate: probability that a child chromosome is mutated after crossover.
    ///
    /// Range: (0,1]
    #[arg(long, default_value_t = 0.3)]
    pub mutation_rate: f32,
    /// Mutation rate decay factor. After each generation, the effective mutation rate
    /// is multiplied by this factor. A decay of 0 means that no decay occurs. A decay
    /// of 0.5 means that after every generation, the effective mutation rate is halved.
    /// This allows aggressive exploration early on and fine-tuning as the population converges.
    ///
    /// Range: [0,1]
    #[arg(long, default_value_t = 0.3)]
    pub mutation_rate_decay: f32,
    /// Minimum mutation rate after decay. The effective mutation rate will never drop below this.
    ///
    /// Range: (0,1]
    #[arg(long, default_value_t = 0.01)]
    pub mutation_rate_min: f32,

    /// Immigration can result in very poor chromosomes and might thus be very costly. We want to
    /// avoid immigration to occur in every evolution step. Setting the value to less than
    /// 1 / population_size ensures this.
    ///
    /// Range: (0,1]
    #[arg(long, default_value_t = 1.0)]
    pub immigration_rate: f32,
    /// Minimum median relative score change required to trigger immigration.
    #[arg(long, default_value_t = 0.075)]
    pub immigration_change_threshold: f32,
    /// Minimum robust z-like score required to trigger immigration.
    /// This is the ratio of median change to MAD (median absolute deviation).
    /// Higher values require more consistent shifts across chromosomes, filtering
    /// out random noise while still detecting genuine workload changes.
    #[arg(long, default_value_t = 10.0)]
    pub immigration_robustness_threshold: f32,
    /// Minimum number of comparable chromosomes needed before trigger detection is active.
    ///
    /// Although it may seem unlikely that 5 of the 20 chromosomes have similar scores, as
    /// chromosomes initially spread the configuration space, note that as the controller
    /// converges, chromosomes will start to cluster together, resulting in similar scores.
    /// Thus, this happens to produce exactly the behaviour we want: before convergence immigration
    /// is unlikely to trigger, which is good because we have no way of telling whether score
    /// changes are due to workload shifts or just the exploration process. After convergence
    /// chromosomes are more similar, and score changes are more likely to be due to workload shifts.
    #[arg(long, default_value_t = 5)]
    pub immigration_min_matched_scores: usize,
    /// Maximum allowed per-parameter change when reusing a previous score.
    #[arg(long, default_value_t = 0.03)]
    pub immigration_similarity_threshold: f32,
    /// Number of generations to wait before allowing immigration to trigger again.
    #[arg(long, default_value_t = 3)]
    pub immigration_cooldown_generations: usize,
}

impl GeneticController {
    /// Instead of randomly initialized values, use an even spread over valid thread
    /// counts and power limits to reduce duplication and increase the chances of
    /// finding an optimum immediately.
    pub fn new(config: GeneticConfig, capabilities: &Capabilities) -> Self {
        let population = (0..config.population_size)
            .map(|mut i| {
                if config.initial_population_descending {
                    i = config.population_size - i - 1;
                }

                let t = i as f32 / (config.population_size - 1) as f32;

                let num_threads = if config.do_thread_control {
                    lerp(1.0, capabilities.max_threads.max(1) as f32, t).round() as u16
                } else {
                    capabilities.max_threads.max(1)
                };

                let power_pct = if config.do_power_control {
                    lerp(config.power_min, config.power_max, t)
                } else {
                    1.0
                };

                Chromosome::new(num_threads, power_pct)
            })
            .collect();

        log::trace!("Init: {:?}", population);

        Self {
            samples: Vec::with_capacity(config.population_size),
            population,
            immigration_cooldown: config.immigration_cooldown_generations,
            sort_descending: !config.initial_population_descending,
            max_threads: capabilities.max_threads.max(1),
            effective_survival_rate: config.survival_rate,
            effective_mutation_rate: config.mutation_rate,
            config,
            generation: 0,
            immigration_was_triggered: false,
        }
    }

    /// Returns the current generation number.
    pub fn generation(&self) -> usize {
        self.generation
    }

    /// Returns whether immigration was triggered during the most recent evolution.
    /// This flag is reset at the start of each evolve() call.
    pub fn immigration_triggered(&self) -> bool {
        self.immigration_was_triggered
    }
}

impl Controller for GeneticController {
    /// Use the number of samples to determine the current index into the population.
    /// The population is reset every `population_size` iterations.
    /// In between, we want every chromosome to be applied once.
    fn get_demand(&mut self) -> Demand {
        debug_assert!(self.samples.len() < self.population.len());
        let chromosome = &mut self.population[self.samples.len()];

        let num_threads = if self.config.do_thread_control {
            chromosome.num_threads.clamp(1, self.max_threads.max(1))
        } else {
            self.max_threads.max(1)
        };

        let powercap_pct = if self.config.do_power_control {
            chromosome.power_pct
        } else {
            1.0
        };

        chromosome.global_thread_count = Some(STATE.thread_utilization());

        Demand {
            num_threads,
            powercap_pct,
        }
    }

    fn push_sample(&mut self, sample: Sample) {
        // Store the global thread count at the time this sample was taken, so we can use it to compute alignment later.
        // Before calling push_sample, the server has already subtracted this chromosome's thread count from the global count.
        let before = self.population[self.samples.len()].global_thread_count.unwrap();
        let total = before + STATE.thread_utilization();
        self.population[self.samples.len()].global_thread_count = Some(total / 2);

        self.samples.push(sample);

        if self.samples.len() >= self.config.population_size {
            self.evolve();
            self.samples.clear();
        }
    }
}

impl GeneticController {
    fn evolve(&mut self) {
        self.generation += 1;
        self.immigration_was_triggered = false;

        let GeneticConfig {
            energy_preference,
            survival_rate,
            survival_rate_decay,
            immigration_rate,
            immigration_change_threshold,
            immigration_cooldown_generations,
            immigration_min_matched_scores,
            immigration_robustness_threshold,
            mutation_rate,
            mutation_rate_decay,
            mutation_rate_min,
            ..
        } = self.config;

        let scores = score(&self.samples, energy_preference);

        log::debug!("Generation {}: best_score={:.4}, worst_score={:.4}, median_score={:.4}",
            self.generation,
            scores.iter().cloned().reduce(f32::min).unwrap_or(0.0),
            scores.iter().cloned().reduce(f32::max).unwrap_or(0.0),
            {
                let mut s = scores.clone();
                s.sort_by(f32::total_cmp);
                s[s.len() / 2]
            }
        );

        let change_detected = update_prev_scores_and_check_for_shift(
            &mut self.population,
            &scores,
            immigration_change_threshold,
            immigration_robustness_threshold,
            immigration_min_matched_scores,
        );

        let population_size = self.population.len();

        // Ensure at least 1 survivor to avoid empty range panic in crossover selection.
        let survival_count = {
            let survival_count = population_size as f32 * self.effective_survival_rate;
            let survival_remainder = survival_count.fract();
            let mut survival_count = survival_count.floor() as usize;
            if rand::random_bool(survival_remainder as f64) {
                survival_count += 1;
            }
            survival_count.max(1)
        };

        let immigration_start = {
            let do_immigration = if self.immigration_cooldown > 0 {
                self.immigration_cooldown -= 1;
                false
            } else if change_detected {
                self.immigration_cooldown = immigration_cooldown_generations;
                true
            } else {
                false
            };

            if do_immigration {
                self.immigration_was_triggered = true;
                log::info!("Generation {}: immigration triggered, replacing population with spread individuals", self.generation);

                self.effective_survival_rate = survival_rate;
                self.effective_mutation_rate = mutation_rate;

                // When immigration rate is less than 1 / population_size, we use a random
                // chance based on the remainder to ensure immigration can still occur.
                let immigration_count = population_size as f32 * immigration_rate;
                let immigration_remainder = immigration_count.fract();
                let mut immigration_count = immigration_count.floor() as usize;
                if rand::random_bool(immigration_remainder as f64) {
                    immigration_count += 1;
                }

                // If survival_rate + immigration_rate > 1.0, there is some overlap between the two.
                // We decide to favor immigration over survival, meaning that fewer than survival_count chromosomes may survive.
                // To favor survival instead, max by survival_count instead of 0.
                (population_size - immigration_count).max(0)
            } else {
                population_size
            }
        };

        if self.config.do_nudging {
            // Cap the nudge strength to a fraction of this generation's own relative score spread
            let effective_nudge_strength = self.config.nudge_strength
                .min(relative_score_spread(&scores) * self.config.nudge_relative_cap);

            let nudged_scores: Vec<f32> = self.population.iter()
                .zip(&scores)
                .map(|(chromosome, &score)| chromosome.nudged_score(&self.config, score, effective_nudge_strength))
                .collect();

            sort_population_by_score(&mut self.population, nudged_scores);
        } else {
            sort_population_by_score(&mut self.population, scores);
        }

        // Replace chromosomes by children of the best performing chromosomes
        for i in survival_count..immigration_start {
            let parent1 = &self.population[rand::random_range(0..survival_count)];
            let parent2 = &self.population[rand::random_range(0..survival_count)];
            let mut child = parent1.crossover(parent2, &self.config);
            if rand::random_bool(self.effective_mutation_rate as f64) {
                child.mutate(&self.config, self.max_threads);
            }

            self.population[i] = child;
        }

        // Decay rates for next generation
        self.effective_survival_rate = (self.effective_survival_rate * (1.0 - survival_rate_decay)).max(0.0);
        self.effective_mutation_rate = (self.effective_mutation_rate * (1.0 - mutation_rate_decay)).max(mutation_rate_min);
        log::debug!("Generation {}: survival rate={:.3}, mutation rate={:.3}",
            self.generation, self.effective_survival_rate, self.effective_mutation_rate);

        // Fill remaining chromosomes by immigration
        let immigration_count = population_size.saturating_sub(immigration_start);
        for (offset, i) in (immigration_start..population_size).enumerate() {
            self.population[i] = Chromosome::from_spread(offset, immigration_count, &self.config, self.max_threads);
        }

        // To minimise changes in the runtime we sort by the recommended power limit
        // and we oscillate between an increasing and decreasing order.
        if self.sort_descending {
            self.population.sort_by(|a, b| b.partial_cmp(a).unwrap());
        } else {
            self.population.sort_by(|a, b| a.partial_cmp(b).unwrap());
        }
        self.sort_descending = !self.sort_descending;
        log::trace!("Evolve: {:?}", self.population);
    }
}

fn sort_population_by_score(population: &mut Vec<Chromosome>, scores: Vec<f32>) {
    let mut combined: Vec<_> = population.drain(..).zip(scores).collect();
    combined.sort_unstable_by(|(_, a), (_, b)| a.total_cmp(b));
    *population = combined.into_iter().map(|(c, _)| c).collect();
}

/// Detect whether program behaviour shifted between generations.
///
/// We compare only chromosomes with a valid `prev_score`, so the score change is
/// meaningful. Heavily mutated chromosomes are ignored to avoid confusing workload
/// drift with unrelated configuration changes.
/// For each comparable chromosome, we compute the relative score change and take
/// the median. We also compute the median absolute deviation (MAD) of those changes.
/// Immigration triggers only when the median change is large enough and clearly
/// exceeds the spread of the paired deltas.
/// The goal is to answer a local question: did the workload change since the last
/// time these comparable configurations were observed? That keeps the logic simple
/// and avoids state that must be carried across many generations.
fn update_prev_scores_and_check_for_shift(
    population: &mut [Chromosome],
    scores: &[f32],
    change_threshold: f32,
    robustness_threshold: f32,
    min_matched_scores: usize,
) -> bool {
    debug_assert_eq!(population.len(), scores.len());

    let mut deltas = Vec::with_capacity(scores.len());

    for (chromosome, &score) in population.iter_mut().zip(scores.iter()) {
        if let Some(prev_score) = chromosome.prev_score {
            // Use a relative change metric to normalize across regions with different absolute scales.
            let ratio = score / (prev_score + f32::EPSILON);
            deltas.push((ratio - 1.0).abs());
        }
        chromosome.prev_score = Some(score);
    }

    log::debug!("Shift detection: {} comparable chromosomes", deltas.len());
    if deltas.len() < min_matched_scores {
        return false;
    }

    let median_delta = median(&mut deltas);
    log::trace!("Shift detection: delta={:.3}, threshold={:.3}", median_delta, change_threshold);
    if median_delta < change_threshold {
        return false;
    }

    let mut deviations: Vec<_> = deltas.into_iter().map(|delta| (delta - median_delta).abs()).collect();
    let mad = median(&mut deviations);
    let ratio = median_delta / (mad + f32::EPSILON);
    if ratio >= robustness_threshold {
        log::info!("Shift detected: change={:.2}%, robustness={:.2}", median_delta * 100.0, ratio);
        true
    } else {
        false
    }
}

impl Chromosome {
    fn new(num_threads: u16, power_pct: f32) -> Self {
        Self {
            num_threads,
            power_pct,
            prev_score: None,
            global_thread_count: None,
        }
    }

    /// Generate a random chromosome for immigration
    fn rand(config: &GeneticConfig, max_threads: u16) -> Self {
        let num_threads = if config.do_thread_control {
            rand::random_range(1..=max_threads)
        } else {
            max_threads.max(1)
        };

        let power_pct = if config.do_power_control {
            rand::random_range(config.power_min..=config.power_max)
        } else {
            1.0
        };

        Self::new(num_threads, power_pct)
    }

    /// Generate a new chromosome. If the immigration count is <= 3, each chromosome is randomly sampled.
    /// Otherwise, chromosomes are generated using an even spread over the valid search space.
    fn from_spread(index: usize, count: usize, config: &GeneticConfig, max_threads: u16) -> Self {
        debug_assert_ne!(count, 0);
        if count <= 3 {
            return Chromosome::rand(config, max_threads);
        }

        let t = index as f32 / (count - 1) as f32;

        let num_threads = if config.do_thread_control {
            lerp(1.0, max_threads as f32, t).round() as u16
        } else {
            max_threads.max(1)
        };

        let power_pct = if config.do_power_control {
            lerp(config.power_min, config.power_max, t)
        } else {
            1.0
        };

        Self::new(num_threads, power_pct)
    }

    fn crossover(&self, other: &Self, config: &GeneticConfig) -> Self {
        // Use the same ratio for the thread count and power limit, as typically lowering
        // the number of threads enables a reduction in the power limit, and vice versa.
        let t = rand::random_range(0.0..=1.0);
        let tr = 1.0 - t;

        // If both parents are similar (similar thread count and power limit), we use their
        // scores to instantiate the child score. This is needed for immigration detection to
        // work, as it relies on comparing the previous and current scores of similar chromosomes.
        // With the default survival rate of only 15%, not enough prev_scores would survive each
        // generation to result in enough scores to detect a workload shift. By averaging the
        // scores of similar parents, we can ensure that the child has a prev_score that is
        // hopefully representative of its configuration.
        let prev_score = if self.is_similar_to(other, config.immigration_similarity_threshold) {
            match (self.prev_score, other.prev_score) {
                (Some(left), Some(right)) => Some(left * t + right * tr),
                _ => None,
            }
        } else {
            None
        };

        let num_threads = if config.do_thread_control {
            (self.num_threads as f32 * t + other.num_threads as f32 * tr).round() as u16
        } else {
            self.num_threads.max(other.num_threads)
        };

        let power_pct = if config.do_power_control {
            self.power_pct * t + other.power_pct * tr
        } else {
            1.0
        };

        Self { num_threads, power_pct, prev_score, global_thread_count: None }
    }

    /// Add or subtract one thread
    fn mutate(&mut self, config: &GeneticConfig, max_threads: u16) {
        let prev_num_threads = self.num_threads;
        let prev_power_pct = self.power_pct;

        if config.do_thread_control {
            if rand::random_bool(config.mutation_strength as f64) {
                if rand::random_bool(0.5) {
                    self.num_threads = self.num_threads.saturating_sub(1);
                } else {
                    self.num_threads = self.num_threads.saturating_add(1);
                }
                self.num_threads = self.num_threads.clamp(1, max_threads);
            }
        }

        if config.do_power_control {
            self.power_pct += rand::random_range(-config.mutation_strength..=config.mutation_strength);
            self.power_pct = self.power_pct.max(config.power_min).min(config.power_max);
        }

        if self.num_threads != prev_num_threads || (self.power_pct - prev_power_pct).abs() > config.immigration_similarity_threshold {
            self.prev_score = None;
        }
    }

    fn is_similar_to(&self, other: &Self, similarity_threshold: f32) -> bool {
        self.num_threads == other.num_threads
            && (self.power_pct - other.power_pct).abs() <= similarity_threshold
    }

    /// How well this chromosome matches secondary preferences, in [0, 1] where
    /// 1 means perfectly aligned and 0 means maximally misaligned.
    fn alignment(&self, config: &GeneticConfig) -> f32 {
        // Prefer thread counts that, combined with other clients, use no more than the available cores
        let thread_alignment = if config.do_thread_control {
            let total_threads = self.num_threads + self.global_thread_count.expect("global_thread_count must be set at this point");
            if total_threads <= HARDWARE.available_cores() {
                1.0
            } else {
                1.0 - (
                    ((total_threads - HARDWARE.available_cores()) as f32) / HARDWARE.available_cores() as f32
                ).clamp(0.0, 1.0)
            }
        } else {
            1.0
        };

        let power_alignment = if config.do_power_control {
            // Prefer power limits proportional to (1 - energy_preference / 2)
            // So maximum power at runtime-oriented, and half power at energy-oriented
            let target_power = 1.0 - 0.5 * config.energy_preference;
            1.0 - (self.power_pct - target_power).abs().clamp(0.0, 1.0)
        } else {
            1.0
        };

        (thread_alignment + power_alignment) / 2.0
    }

    /// Nudges a raw score towards secondary preferences, bounded to at most `nudge_strength` of the raw score.
    /// See [GeneticConfig::nudge_strength] for why this multiplicative approach is used instead of a fixed offset.
    fn nudged_score(&self, config: &GeneticConfig, score: f32, nudge_strength: f32) -> f32 {
        let alignment = self.alignment(config);
        score * (1.0 - alignment * nudge_strength)
    }
}

impl PartialOrd for Chromosome {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        self.power_pct.partial_cmp(&other.power_pct)
    }
}
