use crate::Demand;

use super::{GeneticConfig, gene::*};

#[derive(Clone, Debug, PartialEq)]
pub struct Chromosome {
    threads: ThreadGene,
    power: PowerGene,
    pinning: PinningStrategy,
    /// The score of this chromosome in the previous generation.
    /// This occurs when the chromosome survived, and mutation did not modify it a lot.
    /// Or when the chromosome was generated by crossover of two similar parents, in which case the score is averaged.
    pub prev_score: Option<f32>,
    /// The global thread count at the time this chromosome was sampled.
    /// This excludes the threads used by this chromosome itself ([ThreadGene]).
    /// Note that this can never be exact, as the thread count may change during a sample's execution time.
    pub global_thread_count: Option<u16>,
}

impl Chromosome {
    fn new(threads: ThreadGene, power: PowerGene, pinning: PinningStrategy) -> Self {
        Self {
            threads,
            power,
            pinning,
            prev_score: None,
            global_thread_count: None,
        }
    }

    pub fn get_demand(&self, max_threads: u16) -> Demand {
        Demand {
            num_threads: self.threads.value(max_threads),
            powercap_pct: self.power.value(),
        }
    }

    /// Generate a chromosome using an even spread over the valid search space, `t` in `[0,1]`.
    pub fn from_t(t: f32, config: &GeneticConfig, max_threads: u16) -> Self {
        Self::new(
            ThreadGene::spread(t, config, max_threads),
            PowerGene::spread(t, config, max_threads),
            PinningStrategy::spread(t, config, max_threads),
        )
    }

    /// Generate a random chromosome for immigration
    pub fn rand(config: &GeneticConfig, max_threads: u16) -> Self {
        Self::new(
            ThreadGene::random(config, max_threads),
            PowerGene::random(config, max_threads),
            PinningStrategy::random(config, max_threads),
        )
    }

    /// Generate a new chromosome. If the immigration count is <= 3, each chromosome is randomly sampled.
    /// Otherwise, chromosomes are generated using an even spread over the valid search space.
    pub fn from_spread(index: usize, count: usize, config: &GeneticConfig, max_threads: u16) -> Self {
        debug_assert_ne!(count, 0);
        if count <= 3 {
            return Chromosome::rand(config, max_threads);
        }

        let t = index as f32 / (count - 1) as f32;
        Chromosome::from_t(t, config, max_threads)
    }

    pub fn crossover(&self, other: &Self, config: &GeneticConfig) -> Self {
        // Use the same ratio for every gene, as e.g. lowering the number of threads
        // typically enables a reduction in the power limit, and vice versa.
        let t = rand::random_range(0.0..=1.0);

        // If both parents are similar across all genes, we use their scores to instantiate the
        // child score. This is needed for immigration detection to work, as it relies on comparing
        // the previous and current scores of similar chromosomes. With the default survival rate
        // of only 15%, not enough prev_scores would survive each generation to result in enough
        // scores to detect a workload shift. By averaging the scores of similar parents, we can
        // ensure that the child has a prev_score that is hopefully representative of its configuration.
        let prev_score = if self.is_similar_to(other, config) {
            match (self.prev_score, other.prev_score) {
                (Some(left), Some(right)) => Some(left * t + right * (1.0 - t)),
                _ => None,
            }
        } else {
            None
        };

        Self {
            threads: self.threads.crossover(&other.threads, t),
            power: self.power.crossover(&other.power, t),
            pinning: self.pinning.crossover(&other.pinning, t),
            prev_score,
            global_thread_count: None,
        }
    }

    pub fn mutate(&mut self, config: &GeneticConfig, max_threads: u16) {
        let prev_threads = self.threads.clone();
        let prev_power = self.power.clone();

        self.threads.mutate(config, max_threads);
        self.power.mutate(config, max_threads);
        self.pinning.mutate(config, max_threads);

        if !self.threads.is_similar_to(&prev_threads, config) || !self.power.is_similar_to(&prev_power, config) {
            self.prev_score = None;
        }
    }

    pub fn is_similar_to(&self, other: &Self, config: &GeneticConfig) -> bool {
        self.threads.is_similar_to(&other.threads, config)
            && self.power.is_similar_to(&other.power, config)
            && self.pinning.is_similar_to(&other.pinning, config)
    }

    /// Nudges a raw score towards secondary preferences, bounded to at most `nudge_strength` of the raw score.
    /// See [GeneticConfig::nudge_strength] for why this multiplicative approach is used instead of a fixed offset.
    pub fn nudged_score(&self, config: &GeneticConfig, score: f32, nudge_strength: f32) -> f32 {
        let alignment = self.alignment(config);
        score * (1.0 - alignment * nudge_strength)
    }

    /// How well this chromosome matches secondary preferences, in [0, 1] where
    /// 1 means perfectly aligned and 0 means maximally misaligned.
    ///
    /// [PinningStrategy] does not currently contribute, as `Free` has no secondary preference to align with.
    pub fn alignment(&self, config: &GeneticConfig) -> f32 {
        let global_thread_count = self.global_thread_count.expect("global_thread_count must be set at this point");
        let thread_alignment = self.threads.alignment(global_thread_count);
        let power_alignment = self.power.alignment(config.energy_preference);

        (thread_alignment + power_alignment) / 2.0
    }
}

impl PartialOrd for Chromosome {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        self.power.value().partial_cmp(&other.power.value())
    }
}
