use crate::{Capabilities, Demand};

use super::gene::*;

#[derive(Debug)]
pub struct Chromosome {
    threads: Option<ThreadGene>,
    pinning: Option<PinningGene>,
    power: Option<PowerGene>,
    /// The score of this chromosome in the previous generation.
    /// This occurs when the chromosome survived, and mutation did not modify it a lot.
    /// Or when the chromosome was generated by crossover of two similar parents, in which case the score is averaged.
    pub prev_score: Option<f32>,
    /// The global thread count at the time this chromosome was sampled.
    /// This excludes the threads used by this chromosome itself ([ThreadGene]).
    /// Note that this can never be exact, as the thread count may change during a sample's execution time.
    pub global_thread_count: Option<u16>,
}

impl Chromosome {
    pub fn rand(capabilities: Capabilities) -> Self {
        Self {
            threads: capabilities.thread_control().then(|| ThreadGene::new(capabilities.max_threads()).rand()),
            pinning: capabilities.pinning_control().then(|| PinningGene::new().rand()),
            power: capabilities.power_control().then(|| PowerGene::new(capabilities.min_power(), capabilities.max_power()).rand()),
            prev_score: None,
            global_thread_count: None,
        }
    }

    pub fn lerp(capabilities: Capabilities, t: f32) -> Self {
        Self {
            threads: capabilities.thread_control().then(|| ThreadGene::new(capabilities.max_threads()).lerp(t)),
            pinning: capabilities.pinning_control().then(|| PinningGene::new().lerp(t)),
            power: capabilities.power_control().then(|| PowerGene::new(capabilities.min_power(), capabilities.max_power()).lerp(t)),
            prev_score: None,
            global_thread_count: None,
        }
    }

    /// Generate a new chromosome. If the immigration count is <= 3, each chromosome is randomly sampled.
    /// Otherwise, chromosomes are generated using an even spread over the valid search space.
    pub fn immigrate(index: usize, count: usize, capabilities: Capabilities) -> Self {
        debug_assert_ne!(count, 0);
        if count <= 3 {
            return Chromosome::rand(capabilities);
        }

        let t = index as f32 / (count - 1) as f32;
        Chromosome::lerp(capabilities, t)
    }

    pub fn get_demand(&mut self, capabilities: Capabilities) -> Demand {
        let utilization = self.global_thread_count
            .expect("Thread utilisation must be set at this point");
        Demand {
            num_threads: self.threads.as_mut().map_or(capabilities.max_threads(), |gene| gene.get_num_threads(utilization)),
            powercap_pct: self.power.as_ref().map_or(capabilities.max_power(), |gene| gene.get_powercap()),
        }
    }

    pub fn crossover(&self, other: &Self, immigration_similarity_threshold: f32) -> Self {
        // Use the same ratio for every gene, as e.g. lowering the number of threads
        // typically enables a reduction in the power limit, and vice versa.
        let t = rand::random_range(0.0..=1.0);

        // If both parents are similar across all genes, we use their scores to instantiate the
        // child score. This is needed for immigration detection to work, as it relies on comparing
        // the previous and current scores of similar chromosomes. With the default survival rate
        // of only 15%, not enough prev_scores would survive each generation to result in enough
        // scores to detect a workload shift. By averaging the scores of similar parents, we can
        // ensure that the child has a prev_score that is hopefully representative of its configuration.
        let prev_score = if self.is_similar_to(other, immigration_similarity_threshold) {
            match (self.prev_score, other.prev_score) {
                (Some(left), Some(right)) => Some(left * t + right * (1.0 - t)),
                _ => None,
            }
        } else {
            None
        };

        Self {
            threads: self.threads.crossover(&other.threads, t),
            pinning: self.pinning.crossover(&other.pinning, t),
            power: self.power.crossover(&other.power, t),
            prev_score,
            global_thread_count: None,
        }
    }

    pub fn mutate(&mut self, strength: f32, immigration_similarity_threshold: f32) {
        let mut prev_score_reusable = true;
        prev_score_reusable &= self.threads.mutate(strength) >= (1.0 - immigration_similarity_threshold);
        prev_score_reusable &= self.pinning.mutate(strength) >= (1.0 - immigration_similarity_threshold);
        prev_score_reusable &= self.power.mutate(strength) >= (1.0 - immigration_similarity_threshold);
        if !prev_score_reusable {
            self.prev_score = None;
        }
    }

    pub fn is_similar_to(&self, other: &Self, immigration_similarity_threshold: f32) -> bool {
        let mut similar = true;
        similar &= self.threads.similarity(&other.threads) >= (1.0 - immigration_similarity_threshold);
        similar &= self.pinning.similarity(&other.pinning) >= (1.0 - immigration_similarity_threshold);
        similar &= self.power.similarity(&other.power) >= (1.0 - immigration_similarity_threshold);
        similar
    }

    /// Nudges a raw score towards secondary preferences, bounded to at most `nudge_strength` of the raw score.
    /// See [GeneticConfig::nudge_strength] for why this multiplicative approach is used instead of a fixed offset.
    pub fn nudged_score(&self, score: f32, nudge_strength: f32, energy_preference: f32) -> f32 {
        let alignment = self.alignment(energy_preference);
        score * (1.0 - alignment * nudge_strength)
    }

    /// How well this chromosome matches secondary preferences, in [0, 1] where
    /// 1 means perfectly aligned and 0 means maximally misaligned.
    pub fn alignment(&self, energy_preference: f32) -> f32 {
        let global_thread_count = self.global_thread_count
            .expect("Thread utilisation must be set at this point");
        let thread_alignment = self.threads.as_ref().map(|gene| gene.alignment(global_thread_count)).unwrap_or(1.0);
        let power_alignment = self.power.as_ref().map(|gene| gene.alignment(energy_preference)).unwrap_or(1.0);
        (thread_alignment + power_alignment) / 2.0
    }
}

impl PartialEq for Chromosome {
    fn eq(&self, other: &Self) -> bool {
        self.threads == other.threads
            && self.pinning == other.pinning
            && self.power == other.power
    }
}

impl PartialOrd for Chromosome {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        match (&self.power, &other.power) {
            (Some(a), Some(b)) => a.partial_cmp(&b),
            _ => Some(std::cmp::Ordering::Equal),
        }
    }
}
