[package]
name = "controller"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
non-dominated-sort = "0.3.1"
permutation = "0.4.1"
rand = "0.9.1"

[build-dependencies]
cbindgen = "0.28.0"
