[package]
name = "controller"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
non-dominated-sort = "0.3.1"
rand = "0.9.2"

[build-dependencies]
cbindgen = "0.29.0"
