name: Release

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        release_name: Release
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/{letterbox.h,server}
        file_glob: true
        overwrite: true
